[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_starter = "GfHrF6mrJEPCu57UGK34d8Jht4ntm86siVqHNGo7SYNA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mike/.config/solana/dev-phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 25000