[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_escrow_2023 = "5rJDGSxbwrbi6CB2MgZKV3Q2gLwr9Bx9vYuiC9wv6h7X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mike/.config/solana/dev-phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 25000