[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "GYatJTRxmLz6K6xMuNY9dprfbtLj8jZJ46TpRAqYk8wL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mike/.config/solana/dev-phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000
